### ISSUE TITLE
Provisioning script fails with error unable to add Microsoft.ServiceBus.dll to the script

### ISSUE THREAD

**Issue by rajinders** [mspnp/data-pipeline#24]
I cloned the repository to my local  PC.
I built the solution.
I ran the provisionassets.ps1 and provided the parameters.

It failed with the following error.
Adding the [Microsoft.ServiceBus.dll] assembly to the script...
C:\git\data-pipeline\src\Provisioning\CreateEventHub.ps1 : Could not add the Microsoft.ServiceBus.dll assembly to the
script. Make sure you build the solution before running the provisioning script.
At C:\git\data-pipeline\src\Provisioning\ProvisionAssets.ps1:85 char:1
+ .\CreateEventHub.ps1 -Namespace $ServiceBusNamespace -Path $ServiceBu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,CreateEventHub.ps1

**Comment by rajinders** [comment]
This is not an issue. Since the solution has so many projects and nuget packages take a little while to restore my build was not complete before I tried provisioning.

**Comment by bennage** [comment]
Thanks for logging the issue though.
