### ISSUE TITLE
NLogWrapper methods with activityid

### ISSUE THREAD

**Issue by rajinders** [mspnp/data-pipeline#35]
I was hoping to use ActivityID when logging each of my application. I am aggregating all my log messages in logentries or loggy. Having activityid will make is easier to search for all the messages with a specific activity id.

NLogWrapper does define methods with activityid but most of them are not implemented.
It will be helpful to have at least one method implemented so it can help folks who are not familiar with NLog. 

Is it better to add "ActivityID" as a property for the logEvent.Properties or should we just concatenate the activityid with the message body? I am leaning towards the first option as it will allow me to use a custom layout renders and pass this value separately.

One of the methods is taking in activityId but ignoring it.
This method should either implement the code to pass activityId or throw NotImplementedException as the other methods are doing.

        public void Info(object message, Guid? activityId)
        {
            this._log.Info(message);
        }

**Comment by mabsimms** [comment]
Good catch - let me update the wrapper; agree that it's better to add the activity ID as a property to have more structured for stores like loggly.

**Comment by bennage** [comment]
We've merged in @mabsimms's changes. Please let us know if you find anything else!
