### ISSUE TITLE
Deploying ColdStorage in a separate Cloud Service

### ISSUE THREAD

**Issue by rajinders** [mspnp/data-pipeline#37]
I am using both dispatcher and cold storage worker roles in my current project.
I am considering moving the cold storage worker role into a separate cloud service.
Even though cloud storage and dispatcher read from the same eventhub they perform different functions and may change at different times. Rolling upgrades are awesome but I prefer leaving unchanged services alone instead of updating both dispatcher and cold storage services at the same time even though only one of them has changed.

Another minor pain point has to do with the current state of diagnostics in SDK 2.5.
I wanted to use separate diagnostics accounts for cold storage and dispatcher worker role.
Since both cold storage and dispatcher are packaged in the same cloud service project I was unable to manually deploy the service. Public profile does not allow me to include more than one diagnostic account.

I wanted to see if MSPNP has any opinion about this.

**Comment by bennage** [comment]
I would recommend deploying them as seperate cloud services. In addition to the reasons you listed, each consumer may have different scale out characteristics.
This aligns with the spirit of Event Hub; to have have consumer groups operate entirely independent of one another.
